name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: vatsimnetwork/actions/.github/workflows/build-and-trigger.yml@v1
    with:
      app: discord-tools-bot
    secrets: inherit
